Ev3devJoints:
  Joint_A:
    speed_pid: [1003, 61 , 1] 
    mode: velocity
  Joint_B:
    speed_pid: [1003, 61, 1] 
    mode: velocity
  Joint_C:
    speed_pid: [1003 , 63, 3] 
    mode: velocity
  Joint_D:
    speed_pid: [1004 , 64, 4] 
    mode: velocity

# Publish all joint states -----------------------------------
OutPortState:
  type: joint_state_controller/JointStateController
  publish_rate: 10

# Joint velocity controller
OutPortA:
  type: velocity_controllers/JointVelocityController
  joint: Joint_C

OutPortB:
  type: velocity_controllers/JointVelocityController
  joint: Joint_D
 
####
diffDrv:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'Joint_A'
  right_wheel : 'Joint_B'
  publish_rate: 10.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  #pose_covariance_diagonal : [0.00, 0.00, 0, 0, 0, 0]
  #twist_covariance_diagonal: [0.00, 0.00, 0, 0, 0, 0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.128
  wheel_radius : 0.02

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1 # default: 1.0
  wheel_radius_multiplier    : 1 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 5

  # Base frame_id
  base_frame_id: wheel_link #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      min_velocity           : -1.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # m/s^2
      min_acceleration       : 0.2# m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 10 # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10  # rad/s^2